package edu.ttu;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
//	@Autowired // This means to get the bean called userRepository
//	           // Which is auto-generated by Spring, we will use it to handle the data
//	private UserRepository userRepository;

    private List<User> userlist = new ArrayList<>();
    private AtomicInteger idGen = new AtomicInteger(0);

    @PostMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody
    GenericResult addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setId(idGen.incrementAndGet());
        n.setName(name);
        n.setEmail(email);
        //userRepository.save(n);
        userlist.add(n);

        System.out.println("/demo/add has been successfully executed at server side.");

        return new GenericResult(1, "Success");
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        System.out.println("/demo/all has been successfully executed at server side.");
        return this.userlist;
    }
}
